# docker-compose.yml
version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vidyanav-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    volumes:
      - ./creds.json:/app/creds.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
